### ISSUE TITLE
Invalid hook call.

### ISSUE THREAD

**Issue by lacdael** [orbitdb/orbitdb#1012]
example/src/index.js was added to a freshly created reactjs app, resulting in the following:
  
"Invalid hook call. Hooks can only be called inside of the body of a function component"
  
  https://reactjs.org/docs/error-decoder.html/?invariant=321
  
  ```
  Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at D (react.production.min.js:19:1)
    at exports.useState (react.production.min.js:25:1)
    at n (useIpfs.js:9:1)
    at l (OrbitProvider.js:9:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```
  
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-orbitdb": "^1.0.3",

P.S. great work.

**Comment by haydenyoung** [comment]
Does this problem still occur with orbitdb v1? Also, I'm not aware of react-orbitdb. Closing for now but please re-open if your problems persist.
