### ISSUE TITLE
[commonjs--resolver] No known conditions for "./cid" entry in "multiformats" package when using Sveltekit

### ISSUE THREAD

**Issue by AwesomeKalin** [orbitdb/orbitdb#1042]
System Info:
OS: Windows 11 21H2
CPU: Intel Core i3-10105
RAM: 8GB

Code: 
`<script>
	import * as IPFS from 'ipfs-core'
    import { onMount } from 'svelte';
    import * as Orbit from 'orbit-db';

onMount(async () => {
    const ipfs = await IPFS.create();
    console.log('IPFS Node started');

    const orbitdb = await Orbit.createInstance(ipfs)
    const db = await orbitdb.create('test', 'eventlog');
    console.log(db.address);
});
</script>

<main>
	<slot />
</main>`
Error:
`D:\Code\You-apply-for-a-job-at-McDonalds>pnpm run build

> you-apply-for-a-job-at-mcdonalds@0.0.1 build D:\Code\You-apply-for-a-job-at-McDonalds
> vite build

vite v4.0.4 building for production...
✓ 34 modules transformed.
transforming (50) node_modules\.pnpm\ipfs-core@0.17.0\node_modules\ipfs-core\src\components\refs\local.js14:25:57 [vite-plugin-svelte] dom compile done.
package                                 files    time      avg
you-apply-for-a-job-at-mcdonalds            4   0.15s   36.5ms
[commonjs--resolver] No known conditions for "./cid" entry in "multiformats" package
file: D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/orbit-db@0.28.7/node_modules/orbit-db/src/OrbitDB.js
error during build:
Error: No known conditions for "./cid" entry in "multiformats" package
    at bail (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:14799:8)
    at resolve$1 (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:14856:32)
    at resolveExports (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21865:12)
    at resolveDeepImport (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21883:31)
    at tryNodeResolve (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21572:20)
    at Object.resolveId (file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21336:28)
    at file:///D:/Code/You-apply-for-a-job-at-McDonalds/node_modules/.pnpm/rollup@3.9.1/node_modules/rollup/dist/es/shared/rollup.js:23660:40
 ELIFECYCLE  Command failed with exit code 1.`

Is an issue with orbit, as ipfs works just fine alone

**Comment by anarkrypto** [comment]
You can try: https://github.com/orbitdb/orbit-db/issues/1023#issuecomment-1300931772

**Comment by haadcode** [comment]
This should be fixed in 1.0.0. Note the [new package name](https://www.npmjs.com/package/@orbitdb/core).

If the issue persists, feel free to re-open the issue.
