### ISSUE TITLE
🐛 `npm install -g orbit-db` giving this error. 🐛

### ISSUE THREAD

**Issue by hemangjoshi37a** [orbitdb/orbitdb#1055]
```
(base) hemang@hemang-HP-Pavilion-g6-Notebook-PC:~$ npm install -g orbit-db
npm WARN deprecated electron-download@3.3.0: Please use @electron/get moving forward.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/orbit-db/node_modules/go-ipfs
npm ERR! command failed
npm ERR! command sh -c node src/post-install.js
npm ERR! https://dist.ipfs.tech/go-ipfs/versions
npm ERR! TypeError: Cannot read properties of undefined (reading 'linux')
npm ERR!     at getDownloadURL (/usr/local/lib/node_modules/orbit-db/node_modules/go-ipfs/src/download.js:156:22)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async download (/usr/local/lib/node_modules/orbit-db/node_modules/go-ipfs/src/download.js:177:15)
npm ERR!     at async module.exports (/usr/local/lib/node_modules/orbit-db/node_modules/go-ipfs/src/download.js:250:13)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hemang/.npm/_logs/2023-01-20T10_31_20_249Z-debug-0.log
```

**Comment by anarkrypto** [comment]
This is not how you run orbit-db. Have a look at the examples: https://github.com/orbitdb/orbit-db#module-with-ipfs-instance

**Comment by hemangjoshi37a** [comment]
> This is not how you run orbit-db. Have a look at the examples: https://github.com/orbitdb/orbit-db#module-with-ipfs-instance

I think the example that is given in this page is not from python. It is not running in my python environment.

**Comment by haydenyoung** [comment]
Not quite sure what you're trying to accomplish here. Maybe expand on what you are trying to achieve and we can provide you with more guidance.
