### ISSUE TITLE
Error: ipfs unable to find and fetch manifest for this address

### ISSUE THREAD

**Issue by T00rk** [orbitdb/orbitdb#1077]
I try to create a simple database to query between two nodes.

I have two TS files.

`server.ts`
```typescript
import { v4 as uuid } from 'uuid';

import { OrbitWapper, ODBKeyValue } from 'hsp-orbit-wrapper';

const start = async() =>
{
  await OrbitWapper.Connect();

  const db = new ODBKeyValue<string>(OrbitWapper, { path: 'AZERTY' });

  db.onReplicated(() => console.log('Replicated'));

  await db.init();
  console.log(db.Address);

  setInterval(async () =>
  {
    const x = await db.set(uuid(), uuid());
    console.log(x);
  }, 10000);
}

start();
```
`client.ts`
```typescript
import { OrbitWapper, ODBKeyValue } from 'hsp-orbit-wrapper';

const dba = 
{
  root: 'zdpuAnYMKfYJuoHE13LgEor2m84gBkVu6qL6QeBmxDPCPd3W3',
  path: 'AZERTY'
}

const start = async() =>
{
  await OrbitWapper.Connect();

  const db = new ODBKeyValue<string>(OrbitWapper, dba);

  db.onReplicated(() => console.log('Replicated'));

  await db.init();
  console.log(db.Address);

  setInterval(async () =>
  {
    console.log(db.all())
  }, 1000);
}

start();
```

`server.ts` creates a KVStore and inserts data every 10 seconds.
`client.ts` connects to the existing DB and reads data every second.

The problem here is `client.ts` can't connect to existing DB.
Everytime I get the following error :

```bash
TimeoutError: request timed out
    at maybeThrowTimeoutError (file:///mnt/p2p/node_modules/ipfs-core-utils/src/with-timeout-option.js:41:15)
    at file:///mnt/p2p/node_modules/ipfs-core-utils/src/with-timeout-option.js:97:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Module.read (file:///mnt/p2p/node_modules/orbit-db-io/src/index.js:63:17)
    at OrbitDB.open (file:///mnt/p2p/node_modules/orbit-db/src/OrbitDB.js:455:18)
    at ODBKeyValue.open (/mnt/p2p/packages/common/orbit-wrapper/dist/lib/classes/odb/ODB.js:45:20)
    at /mnt/p2p/packages/common/orbit-wrapper/dist/lib/classes/odb/ODB.js:18:17 {
  code: 'ERR_TIMEOUT'
}
Error: ipfs unable to find and fetch manifest for this address.
    at OrbitDB.open (file:///mnt/p2p/node_modules/orbit-db/src/OrbitDB.js:460:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ODBKeyValue.open (/mnt/p2p/packages/common/orbit-wrapper/dist/lib/classes/odb/ODB.js:45:20)
    at /mnt/p2p/packages/common/orbit-wrapper/dist/lib/classes/odb/ODB.js:18:17
[ERROR] 14:06:27 Error: ipfs unable to find and fetch manifest for this address.
```

**Comment by uninstalls** [comment]
Have you solved this problem yet?

**Comment by mar1n3r0** [comment]
Same here, preceded by:

> unable to open database: unable to fetch database manifest: context deadline exceeded

any request after that:

> unable to create data store used by keystore: resource temporarily unavailable

Tried deleting the LOCK file. The manifest file is there.

**Comment by haydenyoung** [comment]
This may be an underlying IPFS issue. Have you tried against the version 1 code base?

**Comment by haydenyoung** [comment]
Closing this issue due to inactivity. However, if more information can provided based on OrbitDb version 1, please feel free to reopen this issue.
