### ISSUE TITLE
docker run does not work

### ISSUE THREAD

**Issue by scenaristeur** [orbitdb/orbitdb#1107]
using the docker-compose branch 
i 've got this error 

```
docker run -ti --rm orbit-db npm run examples:node

> orbit-db@0.26.0 examples:node /home/node
> node examples/eventlog.js

/home/node/node_modules/multibase/src/util.js:3
const textDecoder = new TextDecoder()
                    ^

ReferenceError: TextDecoder is not defined
    at Object.<anonymous> (/home/node/node_modules/multibase/src/util.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/node/node_modules/multibase/src/base.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! orbit-db@0.26.0 examples:node: `node examples/eventlog.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the orbit-db@0.26.0 examples:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-09-23T14_20_10_725Z-debug.log

```

**Comment by aphelionz** [comment]
Hi, author of the `docker-compose` branch here. That's 3 years old and needs to be updated as `TextDecoder` is a more recent feature. Wanna try to update the versions in the docker-compose file and report back?

**Comment by scenaristeur** [comment]
I don't have time now for that, i just wanted to test orbitdb in a ES6 way, but it seems that all doc is outdated, that's why i have tried docker, but it's the same,

**Comment by haydenyoung** [comment]
Latest documentation is available in the [Github repo](https://github.com/orbitdb/orbitdb/tree/main/docs) and via the [API docs](https://api.orbitdb.org/).

Docker container updates are part of our ongoing upgrade, but with limited resources, we are addressing one item at a time. However, community contributions are always welcome.

Unless there is further information to be added to this issue, I'll close it.
