### ISSUE TITLE
  Error: fetching raw block for CID 

### ISSUE THREAD

**Issue by sloev** [orbitdb/orbitdb#1154]
I have documented my setup in this repo:
https://github.com/sloev/orbitdb-nodejs-local-demo

## Usage

create db:
```bash
$ node create_db.js 13245 FOOBAR
running with port:13245 and ./FOOBAR
clientEventsDb address /orbitdb/zdpuAkn4eb7Xdy5UFCvFGEcYd5HDhufhJHWAgYgVMpWK7U5wF
```

run server
```bash
$ node server.js 13245 FOOBAR  /orbitdb/zdpuAkn4eb7Xdy5UFCvFGEcYd5HDhufhJHWAgYgVMpWK7U5wF
running with port:13245 and ./FOOBAR
clientEventsDb address /orbitdb/zdpuArg5XeMUYwsXT37iuhsSwxJBvuJB4M6FHEdWmmACTkgWq
[]
entry { op: 'ADD', key: null, value: 'hello from ./FOOBAR 1' }
(node:75788) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
entry { op: 'ADD', key: null, value: 'hello from ./FOOBAR 2' }
```

run clients (unique port and directory name!)
```bash
$ node server.js 13255 FOOBARBAZ  /orbitdb/zdpuAkn4eb7Xdy5UFCvFGEcYd5HDhufhJHWAgYgVMpWK7U5wF
running with port:13255 and ./FOOBARBAZ
clientEventsDb address /orbitdb/zdpuArg5XeMUYwsXT37iuhsSwxJBvuJB4M6FHEdWmmACTkgWq
[]
entry { op: 'ADD', key: null, value: 'hello from ./FOOBARBAZ 1' }
(node:76188) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
entry { op: 'ADD', key: null, value: 'hello from ./FOOBARBAZ 2' }
entry { op: 'ADD', key: null, value: 'hello from ./FOOBARBAZ 3' }
```

## errors

```
r➜  saysheep node server.js 13245 FOOBAR  /orbitdb/zdpuAkn4eb7Xdy5UFCvFGEcYd5HDhufhJHWAgYgVMpWK7U5wF
running with port:13245 and ./FOOBAR

(node:78587) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)




node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[AggregateError: All promises were rejected] {
  [errors]: [
    Error: Want for bafyreiaeg347tyzk4o5ixpsgsstemg5u5fhyyui6isuqlhm2qvbbwi54eu aborted
        at EventTarget.<anonymous> (file:///home/nihil/Documents/saysheep/node_modules/ipfs-bitswap/dist/src/notifications.js:56:24)
        at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
        at EventTarget.dispatchEvent (node:internal/event_target:749:26)
        at abortSignal (node:internal/abort_controller:371:10)
        at AbortController.abort (node:internal/abort_controller:393:5)
        at EventTarget.onAbort (file:///home/nihil/Documents/saysheep/node_modules/any-signal/dist/src/index.js:8:20)
        at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
        at EventTarget.dispatchEvent (node:internal/event_target:749:26)
        at abortSignal (node:internal/abort_controller:371:10)
        at AbortController.abort (node:internal/abort_controller:393:5),
    AggregateError: unable to fetch raw block for CID bafyreiaeg347tyzk4o5ixpsgsstemg5u5fhyyui6isuqlhm2qvbbwi54eu from any gateway
        at TrustlessGatewayBlockBroker.retrieve (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/trustless-gateway/broker.js:52:15)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at runNextTicks (node:internal/process/task_queues:64:3)
        at listOnTimeout (node:internal/timers:540:9)
        at process.processTimers (node:internal/timers:514:7)
        at async file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:182:31
        at async Promise.any (index 1)
        at async raceBlockRetrievers (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:179:16)
        at async NetworkedStorage.get (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:91:27)
        at async BlockStorage.get (file:///home/nihil/Documents/saysheep/node_modules/helia/dist/src/storage.js:68:20) {
      [errors]: [
        Error: fetching raw block for CID bafyreiaeg347tyzk4o5ixpsgsstemg5u5fhyyui6isuqlhm2qvbbwi54eu from gateway https://dweb.link/ipfs/bafyreiaeg347tyzk4o5ixpsgsstemg5u5fhyyui6isuqlhm2qvbbwi54eu?format=raw was aborted
            at TrustlessGateway.getRawBlock (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/trustless-gateway/trustless-gateway.js:71:23)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at runNextTicks (node:internal/process/task_queues:64:3)
            at listOnTimeout (node:internal/timers:540:9)
            at process.processTimers (node:internal/timers:514:7)
            at async TrustlessGatewayBlockBroker.retrieve (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/trustless-gateway/broker.js:25:31)
            at async file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:182:31
            at async Promise.any (index 1)
            at async raceBlockRetrievers (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:179:16)
            at async NetworkedStorage.get (file:///home/nihil/Documents/saysheep/node_modules/@helia/block-brokers/dist/src/utils/networked-storage.js:91:27)
      ]
    }
  ]
}

Node.js v20.10.0
```

**Comment by haydenyoung** [comment]
This is possibly a result of Helia running an "in-memory" blockstore; it attempts to retrieve the block, which is in the orbitdb database but helia no longer stores the block because its blockstorage has been wiped.

To rule this out, try setting up [a permanent blockstore](https://github.com/orbitdb/orbitdb/blob/d37d2c9586e493668fb7013fb791be462b4f3e7b/docs/GETTING_STARTED.md#block-storage). 

You can also [find out more about block storage](https://github.com/ipfs-examples/helia-examples/tree/main/examples/helia-101#blockstore) on the Helia site.

**Comment by sloev** [comment]
@haydenyoung thanks for reply, i am indeed using a blockstore as you can see here: https://github.com/sloev/orbitdb-nodejs-local-demo/blob/master/server.js#L34 so that cant be the issue

**Comment by haydenyoung** [comment]
It looks like the two helia peers can't find each other. I opened a [pull request](https://github.com/sloev/orbitdb-nodejs-local-demo/pull/1) on your repo which uses mdns to quickly discovery local peers. This is working for me. Does it work for you?

**Comment by sloev** [comment]
yup, it worked fine! thanks!
