### ISSUE TITLE
Issue with GETTING_STARTED.md page 

### ISSUE THREAD

**Issue by dchicchon** [orbitdb/orbitdb#1169]
Node version - 20.11.1
NPM version - 10.2.4
OS - MacOS

I'm following the getting started page and I got stuck because I got this error
```js
Error: topology must be an instance of interfaces/topology
    at DefaultRegistrar.register (file:///Users/me/app/node_modules/libp2p/dist/src/registrar.js:83:27)
    at Libp2pNode.register (file:///Users/me/app/node_modules/libp2p/dist/src/libp2p.js:343:37)
    at Network.start (file:///Users/me/app/node_modules/@helia/block-brokers/node_modules/ipfs
}
```

Here's the code I have (exactly copied from the getting started I think)

main.js
```
import { createLibp2p } from 'libp2p'
import { createHelia } from 'helia'
import { createOrbitDB } from '@orbitdb/core'
import { LevelBlockstore } from 'blockstore-level'
import { Libp2pOptions } from './config.js'

// Create an IPFS instance.
const blockstore = new LevelBlockstore('./ipfs')
const libp2p = await createLibp2p(Libp2pOptions)
console.log({ blockstore, libp2p, Libp2pOptions });
const ipfs = await createHelia({ libp2p, blockstore })
```

config.js
```
import { tcp } from '@libp2p/tcp'
import { identify } from '@libp2p/identify'
import { gossipsub } from '@chainsafe/libp2p-gossipsub'
import { noise } from '@chainsafe/libp2p-noise'
import { yamux } from '@chainsafe/libp2p-yamux'
import { mdns } from '@libp2p/mdns'

export const Libp2pOptions = {
  peerDiscovery: [
    mdns()
  ],
  addresses: {
    listen: ['/ip4/0.0.0.0/tcp/0']
  },
  transports: [
    tcp()   
  ],
  connectionEncryption: [noise()],
  streamMuxers: [yamux()],
  services: {
    identify: identify(),
    pubsub: gossipsub({ allowPublishToZeroPeers: true })
  }
}
```

**Comment by haydenyoung** [comment]
I was unable to replicate the problem. Could you please provide the version of Helia you have installed?

**Comment by dchicchon** [comment]
Yeah sure, here are my deps
`package.json`
```
{
  "name": "basicapp",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/polyfill": "^7.12.1",
    "@chainsafe/libp2p-gossipsub": "^13.0.0",
    "@orbitdb/core": "^2.1.0",
    "blockstore-level": "^1.1.8",
    "helia": "^4.0.2",
    "ipfs": "^0.66.1",   
  }
}

```

**Comment by haydenyoung** [comment]
I'm still unable to replicate the above problem. A couple of things I can suggest.

Firstly, remove ipfs, you don't need it `npm r ipfs`. 

Secondly, try deleting node_modules and re-install all packages, I.e.

`rm -Rf node_modules`

`npm i`

Also, delete the ipfs directory if it was created:

`rm -Rf ./ipfs`

and see if that resolves the issue. An old module may be hanging around.

**Comment by haydenyoung** [comment]
Feel free to re-open if you can provide additional information about he issue you are experiencing.
