### ISSUE TITLE
[AggregateError: All promises were rejected] - AggregateError: Unable to fetch raw block for CID

### ISSUE THREAD

**Issue by emadridm** [orbitdb/orbitdb#1204]
Hello guys, 

I got the error message when trying to reproduce the "Replicating a database" example of the Getting Started guide (https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md). With console.log() in methods put() and get() of the ipfs-block.js file, I notice the following CIDs in each terminal (see the example):

**Terminal 1**
[ipfs-block]: put() cid =  bafyreidqte5ybho5au6bmpuzva777ctt3e7bu4wnyaanivmtmunxzbuwzy
[ipfs-block]: put() cid =  bafyreigttzcqcdaxcynjtpzln3czjfgbdhvahkou2mh6k2fzdqntzzmva4

**Terminal 2**
[ipfs-block]: get() cid = bafyreihqb76qdfyiebht3we25d6y23atzv7gtk7lhmnu7v7rrstbehrfbi

**Complete error message**
```bash
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[AggregateError: All promises were rejected] {
  [errors]: [
    AggregateError: Unable to fetch raw block for CID bafyreihqb76qdfyiebht3we25d6y23atzv7gtk7lhmnu7v7rrstbehrfbi from any gateway
        at TrustlessGatewayBlockBroker.retrieve (file:///<your-directory>/orbitdb-peer/node_modules/@helia/block-brokers/dist/src/trustless-gateway/broker.js:54:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:353:31
        at async Promise.any (index 0)
        at async raceBlockRetrievers (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:349:16)
        at async NetworkedStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:64:27)
        at async BlockStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/storage.js:71:20)
        at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/ipfs-block.js:65:23)
        at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/composed.js:52:15)
        at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/manifest-store.js:31:23) {
      [errors]: [
        Error: fetching raw block for CID bafyreihqb76qdfyiebht3we25d6y23atzv7gtk7lhmnu7v7rrstbehrfbi from gateway https://4everland.io/ was aborted
            at TrustlessGateway.getRawBlock (file:///<your-directory>/orbitdb-peer/node_modules/@helia/block-brokers/dist/src/trustless-gateway/trustless-gateway.js:105:23)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async TrustlessGatewayBlockBroker.retrieve (file:///<your-directory>/orbitdb-peer/node_modules/@helia/block-brokers/dist/src/trustless-gateway/broker.js:26:31)
            at async file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:353:31
            at async Promise.any (index 0)
            at async raceBlockRetrievers (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:349:16)
            at async NetworkedStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:64:27)
            at async BlockStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/storage.js:71:20)
            at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/ipfs-block.js:65:23)
            at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/composed.js:52:15)
      ]
    },
    AbortError: Want was aborted
        at raceEvent (file:///<your-directory>/orbitdb-peer/node_modules/race-event/dist/src/index.js:129:19)
        at WantList.addEntry (file:///<your-directory>/orbitdb-peer/node_modules/@helia/bitswap/dist/src/want-list.js:79:37)
        at async Bitswap.want (file:///<your-directory>/orbitdb-peer/node_modules/@helia/bitswap/dist/src/bitswap.js:64:28)
        at async file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:353:31
        at async Promise.any (index 1)
        at async raceBlockRetrievers (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:349:16)
        at async NetworkedStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/utils/networked-storage.js:64:27)
        at async BlockStorage.get (file:///<your-directory>/orbitdb-peer/node_modules/@helia/utils/dist/src/storage.js:71:20)
        at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/ipfs-block.js:65:23)
        at async Object.get (file:///<your-directory>/orbitdb-peer/node_modules/@orbitdb/core/src/storage/composed.js:52:15) {
      type: 'aborted',
      code: 'ABORT_ERR'
    }
  ]
}

Node.js v20.17.0
```

**Comment by haydenyoung** [comment]
The documentation you are referring to is archived and out-of-date. Please refer to [the most up-to-date documentation](https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md) for latest configuration.

In particular, your issue is related to a non-persistent blockstore. See the [Blockstore configuration details](https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md#block-storage) for setup.

**Comment by emadridm** [comment]
I probed with [the most up-to-date documentation](https://github.com/orbitdb/orbitdb/blob/main/docs/GETTING_STARTED.md) and got the same error. I have set the IPFS instance with the blockstore and libp2p suggested by the example. Here is my code:

**./config/libp2p.js**
```javascript
import { tcp } from "@libp2p/tcp";
import { identify } from "@libp2p/identify";
import { gossipsub } from "@chainsafe/libp2p-gossipsub";
import { noise } from "@chainsafe/libp2p-noise";
import { yamux } from "@chainsafe/libp2p-yamux";
import { mdns } from "@libp2p/mdns";

export const Libp2pOptions = {
    peerDiscovery: [mdns()],
    addresses: {
        listen: ["/ip4/0.0.0.0/tcp/0"],
    },
    transports: [tcp()],
    connectionEncrypters: [noise()],
    streamMuxers: [yamux()],
    services: {
        identify: identify(),
        pubsub: gossipsub({ allowPublishToZeroTopicPeers: true }),
    },
};
```

**./index.js**
```javascript
import { createLibp2p } from "libp2p";
import { createHelia } from "helia";
import { createOrbitDB, IPFSAccessController } from "@orbitdb/core";
import { LevelBlockstore } from "blockstore-level";
import { Libp2pOptions } from "./config/libp2p.js";

const main = async () => {
    // create a random directory to avoid OrbitDB conflicts.
    let randDir = (Math.random() + 1).toString(36).substring(2);

    const blockstore = new LevelBlockstore(`./${randDir}/ipfs/blocks`);
    const libp2p = await createLibp2p(Libp2pOptions);
    const ipfs = await createHelia({ libp2p, blockstore });

    const orbitdb = await createOrbitDB({
        ipfs,
        directory: `./${randDir}/orbitdb`,
    });

    let db;

    if (process.argv[2]) {
        db = await orbitdb.open(process.argv[2]);
    } else {
        // When we open a new database, write access is only available to the
        // db creator. If we want to allow other peers to write to the database,
        // they must be specified in IPFSAccessController write array param. Here,
        // we simply allow anyone to write to the database. A more robust solution
        // would use the OrbitDBAccessController to provide mutable, "fine-grain"
        // access using grant and revoke.
        db = await orbitdb.open("my-db", {
            AccessController: IPFSAccessController({ write: ["*"] }),
        });

        // Copy this output if you want to connect a peer to another.
        console.log(
            "my-db address",
            "(copy my db address and use when launching peer 2)",
            db.address,
        );
    }

    db.events.on("update", async (entry) => {
        // what has been updated.
        console.log("update", entry.payload.value);
    });

    if (process.argv[2]) {
        await db.add("hello from second peer");
        await db.add("hello again from second peer");
    } else {
        // write some records
        await db.add("hello from first peer");
        await db.add("hello again from first peer");
    }
    // Clean up when stopping this app using ctrl+c
    process.on("SIGINT", async () => {
        // print the final state of the db.
        console.log((await db.all()).map((e) => e.value));
        // Close your db and stop OrbitDB and IPFS.
        await db.close();
        await orbitdb.stop();
        await ipfs.stop();

        process.exit();
    });
};

main();
```

**Comment by haydenyoung** [comment]
The peers are not connecting. Manually dial one peer from the other.

Quickest solution is to pass the address of peer1 to peer2:

```
import { createLibp2p } from "libp2p";
import { createHelia } from "helia";
import { createOrbitDB, IPFSAccessController } from "@orbitdb/core";
import { LevelBlockstore } from "blockstore-level";
import { Libp2pOptions } from "./libp2p-config.js";
import { multiaddr } from '@multiformats/multiaddr'

const main = async () => {
    // create a random directory to avoid OrbitDB conflicts.
    let randDir = (Math.random() + 1).toString(36).substring(2);

    const blockstore = new LevelBlockstore(`./${randDir}/ipfs/blocks`);
    const libp2p = await createLibp2p(Libp2pOptions);
    const ipfs = await createHelia({ libp2p, blockstore });
    const orbitdb = await createOrbitDB({
        ipfs,
        directory: `./${randDir}/orbitdb`,
    });

    let db;

    if (process.argv[2] && process.argv[3]) {
        // manually dial the other peer.
        await orbitdb.ipfs.libp2p.dial(multiaddr(process.argv[2]))
        db = await orbitdb.open(process.argv[3]);
    } else {
        // When we open a new database, write access is only available to the
        // db creator. If we want to allow other peers to write to the database,
        // they must be specified in IPFSAccessController write array param. Here,
        // we simply allow anyone to write to the database. A more robust solution
        // would use the OrbitDBAccessController to provide mutable, "fine-grain"
        // access using grant and revoke.
        db = await orbitdb.open("my-db", {
            AccessController: IPFSAccessController({ write: ["*"] }),
        });

        // Copy this output if you want to connect a peer to another.
        console.log(
            "my-db peerAddress dbAddress",
            "(copy one of the peer addresses and db address to peer 2)",
            libp2p.getMultiaddrs().toString(),
            db.address,
        );
    }

    db.events.on("update", async (entry) => {
        // what has been updated.
        console.log("update", entry.payload.value);
    });

    if (process.argv[2]) {
        await db.add("hello from second peer");
        await db.add("hello again from second peer");
    } else {
        // write some records
        await db.add("hello from first peer");
        await db.add("hello again from first peer");
    }
    // Clean up when stopping this app using ctrl+c
    process.on("SIGINT", async () => {
        // print the final state of the db.
        console.log((await db.all()).map((e) => e.value));
        // Close your db and stop OrbitDB and IPFS.
        await db.close();
        await orbitdb.stop();
        await ipfs.stop();

        process.exit();
    });
};

main();
```
