### ISSUE TITLE
Orbit-db and electron

### ISSUE THREAD

**Issue by nezzard** [orbitdb/orbitdb#309]
Hi, when i run orbit-db with electron i have error
`Non-base58 character
    at Object.decode (C:\final\2\1\node_modules\base-x\index.js:84:11)
    at Object.fromB58String (C:\final\2\1\node_modules\multihashes\src\index.js:68:27)
    at Function.isValid (C:\final\2\1\node_modules\orbit-db\src\orbit-db-address.js:22:74)
    at Function.parse (C:\final\2\1\node_modules\orbit-db\src\orbit-db-address.js:36:25)
    at OrbitDB.create (C:\final\2\1\node_modules\orbit-db\src\OrbitDB.js:230:38)
    at <anonymous>`

How to fix it?

**Comment by RichardLitt** [comment]
Thanks, @nezzard and @ajayrao80. What version are you running? Did you recently run `npm i`?

**Comment by RichardLitt** [comment]
Is there any chance you have an example repo of how you're configuring electron to orbitdb?

**Comment by haydenyoung** [comment]
No further info provided. Closing but feel free to re-open if problems persist.
