### ISSUE TITLE
[Help Wanted] OrbitDB docstore: Syntax error

### ISSUE THREAD

**Issue by mattisstenejohansen** [orbitdb/orbitdb#312]
Hello.
Regarding OrbitDB docstore, I have problems with creating a simple docstore program:

```javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = orbitdb.docstore('database')

docstore.put({ _id: 'hello world', doc: 'all the things' })
  .then(() => docstore.get('hello'))
  .then((value) => console.log(value))
  // [{ _id: 'hello world', doc: 'all the things'}]

```
It returns the following error: 

```
/Users/mattisstene-johansen/node_modules/orbit-db/src/OrbitDB.js:37
  async feed (address, options = {}) {
        ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mattisstene-johansen/Research/test-orbitdb-docstore.js:2:17)
```

Am I doing something wrong or is it a bug? 

Thank you in advance.

**Comment by haadcode** [comment]
@mattisstenejohansen thanks for bringing this up! 👍 

I realized that the documentation for docstore is outdated. [We need to fix that](https://github.com/orbitdb/orbit-db-docstore/issues/10).

`.docstore(...)` now returns a Promise, see the [updated API documentation](https://github.com/orbitdb/orbit-db/blob/master/API.md#docsnameaddress-options), so we need to do:
```js
const db = await orbitdb.docs('database')
// or
orbitdb.docs('database').then(() => ...)
```

IPFS also [needs to be ready](https://github.com/ipfs/js-ipfs#create-a-ipfs-node-instance) before it can be passed to OrbitDB, so to modify your original code a bit, it would look something like this:
```js
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()

ipfs.on('ready', () => {
  const orbitdb = new OrbitDB(ipfs)
  orbitdb.docstore('database')
    .then((docstore) => {
      docstore.put({ _id: 'hello world', doc: 'all the things' })
        .then(() => docstore.get('hello'))
        .then((value) => console.log(value))
        // [{ _id: 'hello world', doc: 'all the things'}]
    })
})
```

Also, what Node.js version are you on? Make sure it's Node.js >= v8.0.0 as we use async/await throughout the code base. If you need to use an older version of Node, there's an ES5 build in `dist/es5` that should work with older versions.

Let me know if this helps!

**Comment by mattisstenejohansen** [comment]
Thanks for the answer, @haadcode. 
I checked, and I was running Node ~v6.x. I updated. I believe that it might be some other error with my dependencies. I'll fix it later. 
If you need help with technical writing, development, etc, I would love to help out.

**Comment by mattisstenejohansen** [comment]
Hello again. 
Does OrbitDB use IPFS-Repo? Because I still run into problems when running the code above. 

```
mattisstene-johansen@Mattis:~$ node test-orbitdb-docstore.js
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: version mismatch: expected v6, found v5
    at get (/Users/mattisstene-johansen/node_modules/ipfs-repo/src/version.js:57:27)
    at store.get (/Users/mattisstene-johansen/node_modules/ipfs-repo/src/version.js:31:9)
    at /Users/mattisstene-johansen/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```
I tried to upgrade and reinstall IPFS-repo manually, but it does no good.
Is this because Orbit uses some specified version (outdated perhaps) of the module?

**Comment by Kotevode** [comment]
Hi.
Have this problem been solved? I think I've got a similar problem:
```
Failed to compile.

Error in ./~/orbit-db/src/OrbitDB.js
Module parse failed: /Users/Maru/dapps/schoolai-final/node_modules/orbit-db/src/OrbitDB.js Unexpected token (37:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (37:8)
 @ ./src/index.js 19:15-34
```

```javascript
//index.js

import React from 'react'
import ReactDOM from 'react-dom'
import IPFS from 'ipfs'
import { Provider } from 'react-redux'
import OrbitDB from 'orbit-db'

import App from './App'
import { types } from './actions'
import store from './store'
import ipfsConfig from './ipfsConfig'

const ipfs = new IPFS(ipfsConfig)

ipfs.on('ready', () => {
  store.dispatch({
    type: types.INIT_IPFS_SUCCESS,
    payload: ipfs
  })
  const orbitdb = new OrbitDB(ipfs)
  store.dispatch({
    type: types.INIT_ORBIT_SUCCESS,
    payload: orbitdb
  })
})

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
```

package.json:
```json
{
  "name": "react-box",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "node": ">= 8.0.0"
  },
  "devDependencies": {
    "autoprefixer": "6.5.1",
    "babel-core": "6.17.0",
    "babel-eslint": "7.1.1",
    "babel-jest": "17.0.2",
    "babel-loader": "6.2.7",
    "babel-preset-react-app": "^2.0.1",
    "case-sensitive-paths-webpack-plugin": "1.1.4",
    "chalk": "1.1.3",
    "connect-history-api-fallback": "1.3.0",
    "cross-spawn": "4.0.2",
    "css-loader": "0.26.0",
    "detect-port": "1.0.1",
    "dotenv": "2.0.0",
    "eslint": "3.8.1",
    "eslint-config-react-app": "^0.5.0",
    "eslint-loader": "1.6.0",
    "eslint-plugin-flowtype": "2.21.0",
    "eslint-plugin-import": "2.0.1",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.4.1",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.9.0",
    "filesize": "3.3.0",
    "fs-extra": "0.30.0",
    "gzip-size": "3.0.0",
    "html-webpack-plugin": "2.24.0",
    "http-proxy-middleware": "0.17.2",
    "jest": "18.1.0",
    "json-loader": "0.5.4",
    "object-assign": "4.1.0",
    "path-exists": "2.1.0",
    "postcss-loader": "1.0.0",
    "promise": "7.1.1",
    "react-dev-utils": "^0.4.2",
    "recursive-readdir": "2.1.0",
    "redux-mock-store": "^1.5.1",
    "strip-ansi": "3.0.1",
    "style-loader": "0.13.1",
    "truffle-contract": "^1.1.8",
    "truffle-solidity-loader": "0.0.8",
    "url-loader": "0.5.7",
    "webpack": "1.14.0",
    "webpack-dev-server": "1.16.2",
    "webpack-manifest-plugin": "1.1.0",
    "whatwg-fetch": "1.0.0"
  },
  "dependencies": {
    "dotenv": "^2.0.0",
    "ipfs": "^0.29.1",
    "orbit-db": "~0.18.7",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-action-creator": "^2.3.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.js?(x)",
      "<rootDir>/src/**/?(*.)(spec|test).js?(x)"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

**Comment by AqeelKazmi** [comment]
Hi @Kotevode 
Can you please share me your directory structure  to configure ipfs, orbitdb, ipfs-pusub-room in reactRedux? If you dont mind

**Comment by haydenyoung** [comment]
Closing. If the latest version of OrbitDb does not address this issue, feel free to re-open this issue.
