### ISSUE TITLE
Unstable orbitdb with swarm address in recent copy

### ISSUE THREAD

**Issue by dexterchan** [orbitdb/orbitdb#333]
I ran the testing with most recent orbitdb with swarm address.
It is unstable in both MAC OS High Sierra: 10.13.3 and GCP Ubuntu 16.04

[TestIPFS_internetSWARM.zip](https://github.com/orbitdb/orbit-db/files/1785630/TestIPFS_internetSWARM.zip)
First node:
under test/firstNode
node testFirstDbNode.js 

Sateillates nodes:
node testSateillates.js --db=<ipfs address from first node>

after running the satellite node for 2 min, without any response for both, 
the first node crash
try insert entries....
get entries...
{name:'dog',pos:'erg'}
/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
      ^
Error: already piped
    at sink (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-pair/index.js:11:13)
    at consume (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-defer/sink.js:7:17)
    at consume (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-defer/sink.js:7:17)
    at pull (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/multistream-select/src/dialer/index.js:47:5)
    at attemptMuxerUpgrade (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/libp2p-switch/src/dial.js:157:10)
    at gotWarmedUpConn (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/libp2p-switch/src/dial.js:54:7)
    at Switch.dial (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/libp2p-switch/src/dial.js:40:9)
    at _getPeerInfo (/home/dexterchan/IPFS_Dist_DB_DEMO/node_modules/libp2p/src/index.js:237:19)

For sateillates, 
also output similar log as the first node....

**Comment by haadcode** [comment]
Possibly related https://github.com/orbitdb/orbit-db/issues/355.

Any updates here @dexterchan, does this still happen for you?

**Comment by haydenyoung** [comment]
Closing as no further feedback. Feel free to re-open if problems persist.
