### ISSUE TITLE
TypeError: fn.apply is not a function

### ISSUE THREAD

**Issue by shaikh-shahid** [orbitdb/orbitdb#806]
I know ipfs-api is replaced with ipfs-http-client, its just one of my project is using that and it was working so didnt change it much. 

However, now i am getting this weird error when tryiing to put data in the database object.

I am using IPFS v 0.18.4

code.

```javascript
const IPFS = require('ipfs-api');
const nconf = require('nconf');
const events = require('events');
const orbitDB = require('orbit-db');
const Identities = require('orbit-db-identity-provider');


async function test() {
    const ipfsOptions = {
        EXPERIMENTAL: {
            pubsub: true
        },
        relay: {
            enabled: true, hop: {
                enabled: true, active: true
            }
        },
        host: 'localhost',
        port: '5001'
    };

    const ipfs = new IPFS(ipfsOptions);
    const IdOptions = { id: 'local-id'};
    const identity = await Identities.createIdentity(IdOptions);
    const orbitdb = new orbitDB(ipfs, identity);
    let handler = await orbitdb.open("/orbitdb/zdpuAzZ6KuqgyTe8LP2rE2bC45cAkst9hM6HfyWmRYZF5Bnyd/maze.mutable.db");
    handler.events.on('ready',async () => {
        console.log("ready");
        let data = await handler.put({_id: 123, name: 'Shahid'});
        let fetchdata = handler.get(123);
        console.log(fetchdata);
    });
    handler.load();
}

test();

```

And the error is the following
```
ready
[ { _id: 123, name: 'Shahid' } ]
/Users/unixroot/Projects/Office/maze-framework/node_modules/once/once.js:25
    return f.value = fn.apply(this, arguments)
                        ^

TypeError: fn.apply is not a function
    at f (/Users/unixroot/Projects/Office/maze-framework/node_modules/once/once.js:25:25)
    at ClientRequest.<anonymous> (/Users/unixroot/Projects/Office/maze-framework/node_modules/ipfs-api/src/utils/send-request.js:71:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:639:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:507:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
```

Surprisingly its happeing after adding the data. Any help pleasEe?

**Comment by tabcat** [comment]
> Surprisingly its happeing after adding the data. Any help pleasEe?

Unfortunately I'm not sure how to handle this and it seems to be a problem, like you mention, with the 'ipfs-api' package so try opening an issue over there? Or try upgrading to ipfs-http-client which is tested with go-ipfs for orbitdb.

**Comment by haydenyoung** [comment]
Closing due to inactivity.
