### ISSUE TITLE
IdentityProvider type 'ethereum' is not supported

### ISSUE THREAD

**Issue by anarkrypto** [orbitdb/orbitdb#952]
The project [orbit-db-identity-provide](https://github.com/orbitdb/orbit-db-identity-provider#creating-an-identity-with-an-ethereum-wallet)  supports **creating an identity with an Ethereum wallet**.

Following the step-by-step, I can connect to my Metamask provider and sign Identity. However, if I try to connect to Orbit-DB using this identity, this is the error I get in Orbit-DB.

```
2022-01-25T08:08:11.186Z [ERROR] orbit-db: Error: IdentityProvider type 'ethereum' is not supported
    at getHandlerFor (/root/services/orbitDB/node_modules/orbit-db-identity-provider/src/identities.js:19:11)
    at Identities.verifyIdentity (/root/services/orbitDB/node_modules/orbit-db-identity-provider/src/identities.js:92:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async saveToIpfs (/root/services/orbitDB/node_modules/orbit-db-store/src/Store.js:317:25)
    at async pEachSeries (/root/services/orbitDB/node_modules/p-each-series/index.js:8:23)
    at async OrbitDB._onMessage (/root/services/orbitDB/node_modules/orbit-db/src/OrbitDB.js:263:11)
```

orbit-db: 0.28.1
orbit-db-identity-provider: 0.4.0

Implemented with Node.JS

**Comment by tabcat** [comment]
My guess is that the orbit-db-identity-provider dependency in orbitdb needs to be updated to version 4

https://github.com/orbitdb/orbit-db/blob/726e667a4f452876271a3a40d22999268cc8a3e2/package.json#L32

**Comment by anarkrypto** [comment]
@tabcat 

Updating the version of **orbit-db-identity-provider** to **^0.4.0** in **orbit-db/package.json** fixed it.
Thank you very much!

I think we'd better make a pull request now, don't you?

**Comment by haydenyoung** [comment]
Thanks for the PR. Closing.
