### ISSUE TITLE
Live Demo 1 doesn't work: Can't connect to remote db

### ISSUE THREAD

**Issue by timaschew** [orbitdb/orbitdb#963]
Recently I even could not open the page, it was just loading forever.

Now the page loads. I can create a local database, but the remote seems to not work. I get this in my firefox console:

```
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/ [QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/)
asm.js type error: Asm.js optimizer disabled because no suitable wasm compiler is available [bundle.js](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Swarm listening on /dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/QmVpe7xeQxp8hXckPPekyXcJzT5RPwTqphuqozarv3tsks [bundle.js:422:134624](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Swarm listening on /dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/QmVpe7xeQxp8hXckPPekyXcJzT5RPwTqphuqozarv3tsks [bundle.js:422:134624](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Swarm listening on /dns4/webrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/p2p/QmVpe7xeQxp8hXckPPekyXcJzT5RPwTqphuqozarv3tsks [bundle.js:422:134624](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details 2
Firefox can’t establish a connection to the server at ws://127.0.0.1:8081/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at ws://127.0.0.1:8081/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at ws://127.0.0.1:8081/p2p/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/p2p/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/p2p/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/p2p/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/p2p/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/p2p/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
GETwss://node3.preload.ipfs.io/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN
[[HTTP/1.1 502 Bad Gateway 296ms]]()

Firefox can’t establish a connection to the server at wss://node3.preload.ipfs.io/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details 2
Firefox can’t establish a connection to the server at wss://sfo-3.bootstrap.libp2p.io/p2p/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://lon-1.bootstrap.libp2p.io/p2p/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://sgp-1.bootstrap.libp2p.io/p2p/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://nyc-2.bootstrap.libp2p.io/p2p/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://ams-1.bootstrap.libp2p.io/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd. [bundle.js:90:201657](https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js)
Firefox can’t establish a connection to the server at wss://nyc-1.bootstrap.libp2p.io/p2p/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm.
```

I've tried to connect to the remote db: `/orbitdb/QmfY3udPcWUD5NREjrUV351Cia7q4DXNcfyRLJzUPL3wPD/hello` unchecking the `read-only` checkbox.

The UI just shows `Connecting to peers...` all the time

**Comment by timaschew** [comment]
Opening it in a incognito tab I receive this errror immedtialy, without pressing any button before:

```
Object { stack: "@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:30204\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:29830\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:15:99260\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:25028\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:6446\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:10074\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:70:6002\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:23:50968\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:33:15707\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:61:80422\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:61:88931\nr@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:110\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:902\n@https://ipfs.io/ipfs/QmUsoSkGzUQnCgzfjL549KKf29m5EMYky3Y6gQp5HptLTG/bundle.js:1:913\n", … }
```

**Comment by timaschew** [comment]
In Chrome (not incognito) I get this when loading the page:

```
Invalid asm.js: Unexpected token
bundle.js:422 Swarm listening on /dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/QmRu14t7cq9eY9mHZBj9SCBYQxHeeL2iiZi2rqWBuvPTSt
bundle.js:422 Swarm listening on /dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/QmRu14t7cq9eY9mHZBj9SCBYQxHeeL2iiZi2rqWBuvPTSt
bundle.js:422 Swarm listening on /dns4/webrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/p2p/QmRu14t7cq9eY9mHZBj9SCBYQxHeeL2iiZi2rqWBuvPTSt
bundle.js:90 WebSocket connection to 'ws://127.0.0.1:8081/p2p/Qmbut9Ywz9YEDrz8ySBSgWyJk41Uvm2QJPhwDJzJyGFsD6' failed: 
e.exports @ bundle.js:90
_connect @ bundle.js:90
dial @ bundle.js:90
dial @ bundle.js:39
dialAction @ bundle.js:90
(anonymous) @ bundle.js:90
bundle.js:90 WebSocket connection to 'ws://127.0.0.1:8081/p2p/QmZMxNdpMkewiVZLMRxaNxUeZpDUb34pWjZ1kZvsd16Zic' failed: 
e.exports @ bundle.js:90
_connect @ bundle.js:90
dial @ bundle.js:90
dial @ bundle.js:39
dialAction @ bundle.js:90
(anonymous) @ bundle.js:90
bundle.js:90 WebSocket connection to 'ws://127.0.0.1:8081/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS' failed: 
e.exports @ bundle.js:90
_connect @ bundle.js:90
dial @ bundle.js:90
dial @ bundle.js:39
dialAction @ bundle.js:90
(anonymous) @ bundle.js:90
bundle.js:90 WebSocket connection to 'wss://node3.preload.ipfs.io/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN' failed: 
```
And when I try to connect to the remote DB I get this:

```
bundle.js:422 Error: 'options.create' set to 'false'. If you want to create a database, set 'options.create' to 'true'.
    at k.open (bundle.js:61:87275)
    at HTMLButtonElement.<anonymous> (bundle.js:422:395125)
```

**Comment by tabcat** [comment]
The errors on load seem fine. There can be a lot of errors from ipfs about connections failing.
Also everything seems to be working for me.
I created a database in one tab, opened it remotely from an incognito tab. This is using chromium.

**Comment by mar1n3r0** [comment]
@tabcat I tried using it with a previously created database(not in js ipfs instance) and it never gets open. Noticed that the multihashes are different as well:

When created from the demo/control-center:
`/orbitdb/zdpuAyPXXpCuZTmnbZ2zPm5hau4mUADAjUh8Qrj2m1pKMagJ4/demands_supplies`

When created outside the browser via the go-ipfs api:
`/orbitdb/bafyreibe2lnmluj2y4byq6dnb4jbyxinvfbiz5lj7myasprln5pqtmcarm/demand_supply`

**Comment by tabcat** [comment]
the cid encoding is different, as well as the actual encoded hash in this case. a different manifest is being created with differing configuration. you need to open the db using the address or figure out what configuration you need to change when creating the db to match the other. im not sure why the cid's use different base encodings.

**Comment by mar1n3r0** [comment]
Thanks, I have inspected it with the CID inspector: 

https://cid.ipfs.io/#zdpuAsm8HoFigBNechuWaUGDgcVR3LyPbZ24BbFYsojd5TvuP

But when I try to open the content via the IPFS-desktop it doesn't show up. It's weird indeed will need further investigation.

**Comment by tabcat** [comment]
the hash is a dag object and is not an ipfs file. they are a bit different and some tools that can read from ipfs can only read ipfs files from the dag.

im not sure what the default CID V1 prefix you are referring to is. `z` is the prefix to show base58btc, the next few letters after that state the CID is version 1, what the cid is describing (a dag-cbor object in this case), and then then the hash digest algorithm.
`<base58btc><cidv1><ipld><multihash>`

my guess is the ipld code is different where you expect it to be an ipfs ipld code but we are using dag-cbor which are like objects instead of files.

https://github.com/multiformats/multicodec/blob/master/table.csv#L44

**Comment by tabcat** [comment]
You bring up an excellent point about opening addresses that use different encodings! I believe how our discovery system works currently they will never find each other! We need to fix that and make sure they can find each other. That is probably better done inside the source than by the web app.

**Comment by tabcat** [comment]
> Got it, so it's the discovery system that is restricted to the z prefix only.

not quite, its that only peers using the same base encoding for the address will find each other.

> The standard CID V0 starts with Qm and V1 starts with ba.

`b` is the prefix for base32 just like `z` is the prefix for base58btc. They are both cidv1. Im not sure if one is specified as the standard/default encoding.

**Comment by mar1n3r0** [comment]
https://docs.ipfs.io/concepts/content-addressing/#cid-inspector

> The default for CIDv1 is the case-insensitive base32

**Comment by haydenyoung** [comment]
Live demo is outdated. Will require further investigation and reimplementation.
