### ISSUE TITLE
Why is it so difficult to build a project with orbit-db and create-react-app???

### ISSUE THREAD

**Issue by arseniy-gl** [orbitdb/orbitdb#988]
```
npx create-react-app ...
```

```
async function main () {
  // Create IPFS instance
  const ipfsOptions = { repo : './ipfs', }
  const ipfs = await IPFS.create(ipfsOptions)

  // Create OrbitDB instance
  const orbitdb = await OrbitDB.createInstance(ipfs)

  const db = await orbitdb.keyvalue('first-database')
  console.log(db.address.toString())
}
```

😤 add polifills:

```
const webpack = require("webpack");

module.exports = function override (config, env) {
  console.log('override')
  let loaders = config.resolve
  loaders.fallback = {
    "path": require.resolve("path-browserify"),
    "stream": require.resolve("stream-browserify"),
    "crypto": require.resolve("crypto-browserify"),
    "util": require.resolve("util/")
  }

  config.plugins.push(
    new webpack.DefinePlugin({process: {env: {}}})
  )
  return config
}
```

... and still errors:

```
_stream_writable.js:57 Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at Object.../orbit-db/node_modules/readable-stream/lib/_stream_writable.js (_stream_writable.js:57:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object.../orbit-db/node_modules/readable-stream/readable-browser.js (readable-browser.js:4:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object.../orbit-db/node_modules/orbit-db-docstore/src/DocumentStore.js (DocumentStore.js:6:1)
    at Object.options.factory (react refresh:6:1)
```

**Comment by haydenyoung** [comment]
Is this still the case with latest OrbitDB release. Feel free to re-open this issue if problems persist.
